### ISSUE TITLE
没有数库文件吗

### ISSUE THREAD

**Issue by 121753961** [1ibrary/1ibrary-back-end#2]
怎么没有数库文件吗

**Comment by airingursb** [comment]
@121753961 这个mock后端只适用于一图的早期版本哦~ [https://github.com/1ibrary/1ibrary-front-end/commit/fdebfdd00f07f34fabd9eb3b5d96b8b947eb7d3d](https://github.com/1ibrary/1ibrary-front-end/commit/fdebfdd00f07f34fabd9eb3b5d96b8b947eb7d3d)

数据库的模拟数据我现在push一份

**Comment by 121753961** [comment]
@airingursb  非常感谢
